name: Node.js CI

on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: npm run lerna -- bootstrap
    - run: npm run lint
    - run: npm run test -- --runInBand
    - uses: codecov/codecov-action@v1
      with:
        file: .coverage/*.json
      env:
        CI: true
        RUN_INTEGRATION: true
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: npm run lerna -- bootstrap
    - run: npm run build
    - run: cd integration-tests && npm run test
      env:
        CI: true
  publish-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'ref/head/master'
    needs: [integration-tests, lint-and-test]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: npm run lerna -- bootstrap
    - run: npm run lerna run build
    - run: cd website && cp -R build/. ../dist
    - run: npm run build-docs
    - run: cd packages/taquito-react-components && npm run build-storybook -- -o ../../dist/react-storybook
    # - run: cd dist && touch .nojekyll && echo 'tezostaquito.io' > CNAME
    - name: Publish generated content to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
      with:
        dir: dist
        branch: gh-pages
        token: ${{ secrets.ACCESS_TOKEN }}
      env:
        CI: true
